### PR TITLE
[WIP] Final revisions and Coverage testing

### LINKED ISSUE #42: Friend request bug
Customer 1 sends Customer 2 a FR.
Customer 2 sends Customer 1 a FR.

Expected behavior: when Customer 2 sends Customer 1 a FR, it should look for and accept Customer 1's FR instead.

### LINKED ISSUE #49: Current bugs
- [x] Remove length check for cvc, replace with 0 <= cvc < 1000
- [x] Change redirect when editing person
- [x] Purchase slot doesn't work; something with the logic...
- [x] Add payment edit form to invoice page
- [x] Video autoplay-next acts strangely
- [x] Favorite button on video player
- [x] Check customer purchased sub or rental before video
- [x] Button style for various producer forms
- [x] Avatar not updating when profile edited
  - Works, but the field will clear if there is an invalid entry and resets (and so it appears like it doesn't work)

### PR DESCRIPTION
**Pull request by Wyvernix**
Presentation is due next Wednesday. We should consider this our final deadline and all changes should be completed before then.

closes #42 
closes #49

### CODE REVIEW

**Comment by Wyvernix** [comment]
All of the bugs I know of are squashed except for creating the payments form. This closes #42. All the features are done except ratings and notification email.

**Comment by SRHarrison13** [comment]
Test cases that need attention:
test "should update friend request"
test "should activate account"

**Comment by Wyvernix** [comment]
So far coverage is at 93% C-0 and 45% C-1. We should first focus on getting C-0 close to 99% and C-1 should increase as well. This should be easy since there is only around 100 branches in the program code. Coverage testing is beneficial in uncovering dead or unused code, and we should consider **removing or refactoring** this code.

**Comment by Wyvernix** [comment]
image

**Comment by SRHarrison13** [comment]
Screen Shot 2019-05-04 at 5 34 54 PM

**Pull request merged**
